libosmo-pfcp.pc: move libosmogsm to Requires
It appears Requires.private is not working as intended. Moving to
Requires seems to fix the problem I am seeing on my machine:

  CCLD     unique_ids_test
 /usr/bin/ld: /usr/local/lib/libosmo-pfcp.so: undefined reference to `osmo_apn_to_str'
 /usr/bin/ld: /usr/local/lib/libosmo-pfcp.so: undefined reference to `osmo_apn_from_str'

Change-Id: I319173c1fab068dfe1361ae6cd02f729461d4cf8